baseURL = "https://rvgef.hk"
languageCode = "en-us"
title = "RISC-V Global Ecosystem Forum"
theme = "rvgef"

[params]
  description = "RISC-V Global Ecosystem Forum - Hong Kong"
  author = "RISC-V Global Ecosystem Forum"
  
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
